# Generated by Django 4.2.7 on 2024-12-04 23:42

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorised_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_no', models.DecimalField(decimal_places=0, help_text='Enter National Identification Number:', max_digits=8, unique=True, validators=[main.validators.validate_kenyan_id])),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=30)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=30)),
                ('email_address', models.EmailField(help_text='Enter Email Address', max_length=50, unique=True)),
                ('username', models.EmailField(help_text='Enter Username', max_length=50, unique=True)),
                ('phone_number', models.CharField(help_text='Enter phone number in the format 0798073204 or +254798073404', max_length=13, validators=[main.validators.validate_kenyan_phone_number])),
            ],
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(help_text='Enter Item Code', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Vehicle', 'Vehicle'), ('Other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(help_text='Enter Item Code', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Vehicle', 'Vehicle'), ('Other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(help_text='Enter Unique Code', max_length=10, unique=True)),
                ('pin', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('serial_number', models.CharField(help_text='Enter Serial Number', max_length=20, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(help_text='Enter Mac Address', max_length=20)),
                ('model', models.CharField(help_text='Enter Model', max_length=50)),
                ('unique_code', models.CharField(help_text='Enter Unique Code', max_length=10, unique=True)),
                ('national_id_no', models.DecimalField(decimal_places=0, help_text='Enter National Identification Number:', max_digits=8, unique=True, validators=[main.validators.validate_kenyan_id])),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_no', models.DecimalField(decimal_places=0, help_text='Enter National Identification Number:', max_digits=8, unique=True, validators=[main.validators.validate_kenyan_id])),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=30)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=30)),
                ('email_address', models.EmailField(help_text='Enter Email Address', max_length=50, unique=True)),
                ('username', models.EmailField(help_text='Enter Username', max_length=50, unique=True)),
                ('phone_number', models.CharField(help_text='Enter phone number in the format 0798073204 or +254798073404', max_length=13, validators=[main.validators.validate_kenyan_phone_number])),
            ],
        ),
        migrations.CreateModel(
            name='System_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(help_text='Enter a valid Username', max_length=50, unique=True)),
                ('password_hash', models.CharField(help_text='Enter a valid password', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('number_plate', models.CharField(help_text='Enter Number Plate', max_length=20, primary_key=True, serialize=False)),
                ('model', models.CharField(help_text='Enter Model', max_length=50)),
                ('unique_code', models.CharField(help_text='Enter Unique Code', max_length=10, unique=True)),
                ('national_id_no', models.DecimalField(decimal_places=0, help_text='Enter National Identification Number:', max_digits=8, unique=True, validators=[main.validators.validate_kenyan_id])),
            ],
        ),
    ]
